language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

branches:
  only:
    - /^build/

after_success:
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla::App::Command::cover Devel::Cover::Report::Coveralls Dist::Zilla::PluginBundle::Author::GABRIEL
  - dzil cover -test
  - dzil cover -report coveralls