language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

branches:
  only:
    - /^build/

after_success:
  - HARNESS_PERL_SWITCHES=-MDevel::Cover=-db,$TRAVIS_BUILD_DIR/cover_db
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cover -report coveralls